module UnivSolverCheck

-- Tests for observable cumulativity behavior.
-- Type 0 ≤ Type 1 (cumulativity): using a smaller universe where a larger
-- one is expected should be allowed.

-- A function that demands its argument has a type in some universe.
-- The Pi rule gives the result a universe ≥ both argument and return type.
f : (a : Type) -> (b : Type) -> (a -> b) -> a -> b
f a b g x = g x

-- Applying f with Type itself as the domain — this forces universe levels
-- to be assigned and checks Pi formation still works.
typeToType : (Type -> Type) -> Type -> Type
typeToType h t = h t

-- Double Pi — the result type is at max of the two argument types.
-- This used to silently be Type : Type; now it's properly stratified.
const2 : (a : Type) -> (b : Type) -> a -> b -> a
const2 a b x y = x

-- Verifying that the solver accepts x ≤ max(x, y) style constraints
-- (generated by Pi formation) — if the solver choked on these the module
-- would fail to build.
piFormation : (a : Type) -> (b : a -> Type) -> Type
piFormation a b = (x : a) -> b x
